// Generated by https://quicktype.io

export interface SinglePetition {
  links: Links;
  data: Data;
}

export interface Data {
  type: string;
  id: number;
  attributes: Attributes;
}

export interface Attributes {
  action: string;
  background: string;
  additional_details: string;
  committee_note: null;
  state: string;
  signature_count: number;
  created_at: string;
  updated_at: string;
  rejected_at: null;
  opened_at: string;
  closed_at: null;
  moderation_threshold_reached_at: string;
  response_threshold_reached_at: string;
  government_response_at: string;
  debate_threshold_reached_at: string;
  scheduled_debate_date: null;
  debate_outcome_at: null;
  creator_name: string;
  rejection: null;
  government_response: GovernmentResponse;
  debate: null;
  departments: Department[];
  topics: string[];
  signatures_by_country: SignaturesByCountry[];
  signatures_by_constituency: SignaturesBy[];
  signatures_by_region: SignaturesBy[];
}

export interface Department {
  acronym: string;
  name: string;
  url: string;
}

export interface GovernmentResponse {
  responded_on: string;
  summary: string;
  details: string;
  created_at: string;
  updated_at: string;
}

export interface SignaturesBy {
  name: string;
  ons_code: string;
  mp?: string;
  signature_count: number;
}

export interface SignaturesByCountry {
  name: string;
  code: string;
  signature_count: number;
}

export interface Links {
  self: string;
}
